version: "3"

services:
  api_proxy:
    build:
      context: api-proxy
    container_name: api-proxy-server
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 5000:5000
    volumes:
      - ./api-proxy:/home/node/app
    environment:
      - PORT=5000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  frontend:
    build:
      context: frontend-react
    container_name: frontend-react
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react:/home/node/app
    depends_on:
      - api_proxy
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
