version: '3'

services:
  
  app:
    build: .
    container_name: api-proxy-server
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app
    environment:
      - PORT=5000